CXX = emcc

SRC_DIR ?= source
WEB_SRC_DIR ?= gclcWeb/src
WEB_PUBLIC_DIR ?= gclcWeb/public
BUILD_DIR ?= build/web
BIN_DIR ?= executable
TARGET_EXEC ?= gclc

SRCS  = wGCLCmain.cpp \
		Export/TikZOutput.cpp \
		Export/SVGOutput.cpp \
		Export/PSTricksOutput.cpp \
		Export/LaTeXOutput.cpp \
		Export/GCLCOutput.cpp \
		Export/EPSOutput.cpp \
		ExpressionParser/parser.cpp \
		GCLCEngine/Transformations.cpp \
		GCLCEngine/TheoremProving.cpp \
		GCLCEngine/LowLevelCommands.cpp \
		GCLCEngine/Layers.cpp \
		GCLCEngine/LabelingCommands.cpp \
		GCLCEngine/GCLC.cpp \
		GCLCEngine/DrawingCommands.cpp \
		GCLCEngine/Cartesian3DCommands.cpp \
		GCLCEngine/Cartesian2DCommands.cpp \
		GCLCEngine/Calculations.cpp \
		GCLCEngine/BasicDefinitions.cpp \
		GCLCEngine/BasicConstructions.cpp \
		GCLCEngine/Animations.cpp \
		GenericEngine/IntermediateRepresentation.cpp \
		GenericEngine/GCompiler.cpp \
		GraphDrawing/settings.cpp \
		GraphDrawing/graph_util.cpp \
		GraphDrawing/graphnode.cpp \
		GraphDrawing/graph.cpp \
		GraphDrawing/drawing.cpp \
		GraphDrawing/barycenterdrawing.cpp \
		GraphDrawing/arclayereddrawing.cpp \
		Input/StringInput.cpp \
		Input/GCLCInput.cpp \
		Input/FileInput.cpp \
		Logging/GCLCLog.cpp \
		Logging/FileLog.cpp \
		Logging/DummyLog.cpp \
		Utils/Utils.cpp \
		Utils/Timer.cpp \
		TheoremProver/WuMethod.cpp \
		TheoremProver/TheoremProver.cpp \
		TheoremProver/ProverExpression.cpp \
		TheoremProver/GroebnerMethod.cpp \
		TheoremProver/AreaMethod.cpp \
		TheoremProver/AlgMethodReducible.cpp \
		TheoremProver/AlgMethod.cpp \
		AlgebraicMethods/XTerm.cpp \
		AlgebraicMethods/xpolynomial.cpp \
		AlgebraicMethods/Wu.cpp \
		AlgebraicMethods/UTerm.cpp \
		AlgebraicMethods/UPolynomialFraction.cpp \
		AlgebraicMethods/UPolynomial.cpp \
		AlgebraicMethods/TermStorageVector.cpp \
		AlgebraicMethods/TermStorageAvl.cpp \
		AlgebraicMethods/TermStorage.cpp \
		AlgebraicMethods/Term.cpp \
		AlgebraicMethods/Reduce.cpp \
		AlgebraicMethods/Prover.cpp \
		AlgebraicMethods/Power.cpp \
		AlgebraicMethods/PolyReader.cpp \
		AlgebraicMethods/Polynomial.cpp \
		AlgebraicMethods/ObjectBank.cpp \
		AlgebraicMethods/Object.cpp \
		AlgebraicMethods/Log.cpp \
		AlgebraicMethods/ITimeOut.cpp \
		AlgebraicMethods/Groebner.cpp \
		Import/ListOfFaces.cpp 

OBJS := $(SRCS:%.cpp=$(BUILD_DIR)/%.o)

CPPFLAGS ?= 
CXXFLAGS = 

LDFLAGS = 

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	@echo Compiling $< ...
	mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

$(BIN_DIR)/$(TARGET_EXEC): $(OBJS)
	@echo Creating $@ 
	$(CXX) $(OBJS) -o gclc.js $(LDFLAGS) \
		-s WASM=1 \
		-s MODULARIZE=1 \
		-O2 \
		-sENVIRONMENT=web \
		-s EXPORTED_FUNCTIONS='["_render", "_malloc", "_free", "_calloc"]' \
		-s EXPORTED_RUNTIME_METHODS='["cwrap", "AsciiToString", "stringToUTF8", "lengthBytesUTF8", "UTF8ToString", "stringToUTF8", "getValue", "FS"]' \
		-s 'EXPORT_NAME="createModule"'
	sed -i '1s;^;\/* eslint-disable *\/;' gclc.js
	sed -i 's/\(if (typeof exports === .object. && typeof module === .object.\)).*/export { createModule };\/*/' gclc.js
	echo '*/' >> gclc.js
	mv gclc.wasm $(WEB_PUBLIC_DIR)
	mv gclc.js $(WEB_SRC_DIR)

.PHONY: clean

clean:
	$(RM) $(WEB_SRC_DIR)/gclc.js
	$(RM) $(WEB_PUBLIC_DIR)/gclc.wasm
	$(RM) gclcWeb/dist/ -R
	$(RM) gclcWeb/node_modules -R

MKDIR_P ?= mkdir -p


