// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  LineComment = 2,
  Statement = 3,
  Identifier = 4,
  Number = 192,
  StatementBlock = 193,
  ExpressionList = 194,
  Sum = 196,
  Product = 197,
  Comparation = 198
